### Added by Zinit's installer
if [[ ! -f $HOME/.zinit/bin/zinit.zsh ]]; then
    print -P "%F{33}▓▒░ %F{220}Installing %F{33}DHARMA%F{220} Initiative Plugin Manager (%F{33}zdharma/zinit%F{220})…%f"
    command mkdir -p "$HOME/.zinit" && command chmod g-rwX "$HOME/.zinit"
    command git clone https://github.com/zdharma-continuum/zinit "$HOME/.zinit/bin" && \
        print -P "%F{33}▓▒░ %F{34}Installation successful.%f%b" || \
        print -P "%F{160}▓▒░ The clone has failed.%f%b"
fi

source "$HOME/.zinit/bin/zinit.zsh"
autoload -Uz _zinit
(( ${+_comps} )) && _comps[zinit]=_zinit
### End of Zinit's installer chunk

### custom configuration
# vi bindings
bindkey -v

# modules (turbo mode)
zinit ice wait'!0'

# colorizes various shell tools (grep, diff, ip, ...)
# NOTE: currently disabled because alpine busybox does not support certain grep options
#zinit light zpm-zsh/colorize
#
# change login terminal colors
if [ "$TERM" = "linux" ]; then
    echo -en "\e]P0242933" #black
    echo -en "\e]P83B4252" #darkgrey
    echo -en "\e]P1BF616A" #darkred
    echo -en "\e]P9BF616A" #red
    echo -en "\e]P2A3BE8C" #darkgreen
    echo -en "\e]PAA3BE8C" #green
    echo -en "\e]P3EBCB8B" #brown
    echo -en "\e]PBEBCB8B" #yellow
    echo -en "\e]P481A1C1" #darkblue
    echo -en "\e]PC81A1C1" #blue
    echo -en "\e]P5B48EAD" #darkmagenta
    echo -en "\e]PDB48EAD" #magenta
    echo -en "\e]P688C0D0" #darkcyan
    echo -en "\e]PE88C0D0" #cyan
    echo -en "\e]P7E5E9F0" #lightgrey
    echo -en "\e]PFD8DEE9" #white
    #clear #for background artifacting
fi

# aliases
source ~/.aliases

# add script and appimage to path
export PATH="$HOME/.scripts:$PATH"
export PATH="$HOME/.appimage:$PATH"
export PATH="$HOME/.bin:$PATH"
export PATH="$HOME/.local/bin:$PATH"

# add golang path
export GOPATH="$HOME/.go"
export GOROOT="${HOME}/.go/go"
export PATH="$PATH:$GOPATH/bin"
export PATH="$PATH:$GOROOT/bin"
export GOSUMDB=sum.golang.org
export GOPROXY=direct

# source theme
source ~/.zsh/theme.zsh

# completion settings
source ~/.zsh/completion-settings.zsh

# change ls colors to match system
source ~/.zsh/completion-colors.zsh

# general settings
source ~/.zsh/general-settings.zsh

# rationalize dot
source ~/.zsh/rationalize-dot.zsh

# vi mode settings
source ~/.zsh/vi-mode.zsh

# tab completion generator
source ~/.zsh/completion-generator.zsh

# fzf integration
source ~/.zsh/fzf-settings.zsh
source ~/.zsh/fzf-completion.zsh
source ~/.zsh/fzf-keybindings.zsh

# fzf tab completion
source ~/.zsh/fzf-tab-completion.zsh

# tab completion github cli
source ~/.zsh/completion-github-cli.zsh

# several fixes for different systems
source ~/.zsh/fixes.zsh

# additional tools
source ~/.zsh/tools.zsh

# additional stuff
if [ "$(uname)" = "Linux" ]; then
  # dont use gui to enter git credentials
  unset SSH_ASKPASS
  # keyboard layout
  #setxkbmap us -variant altgr-intl
  # use caps as escape button
  #setxkbmap -option caps:escape
  #export XDG_RUNTIME_DIR=$HOME/.tmp
fi

# openjdk
export JAVA_HOME="/usr/lib/jvm/default"
export PATH=$PATH:/home/awzm/.spicetify

# add pip local cache to path
export PATH="${PATH}:${HOME}/.local/bin"

# gcloud completion
if [ -f "${HOME}/.completion/gcloud/completion.zsh.inc" ]; then
   source ${HOME}/.completion/gcloud/completion.zsh.inc
fi

# extra completions
command -v gh > /dev/null && . <(gh completion -s zsh)
command -v devpod > /dev/null && . <(devpod completion zsh)
command -v timetrace > /dev/null && . <(timetrace completion zsh)
command -v talosctl > /dev/null && talosctl completion zsh > "${fpath[1]}/_talosctl"
command -v terraform > /dev/null && complete -o nospace -C /home/awzm/.bin/terraform terraform
# set timesheet file
command -v tt > /dev/null && export SHEET_FILE="${HOME}/.timesheets/timesheet.json"

# spicetify
export PATH=${PATH}:${HOME}/.spicetify

# docker aliases completion
source ~/.zsh/completion-aliases-docker.zsh

autoload -U +X bashcompinit && bashcompinit

# Set custom path for completions generated by `zsh-update-completions`
fpath=(~/.zsh/completions $fpath)

# trigger completion initialization
compinit
