k9s:
  liveViewAutoRefresh: false
  refreshRate: 2
  maxConnRetry: 5
  enableMouse: false
  enableImageScan: false
  headless: false
  logoless: true
  crumbsless: true
  readOnly: false
  noExitOnCtrlC: false
  noIcons: false
  shellPod:
    image: busybox:1.35.0
    namespace: default
    limits:
      cpu: 100m
      memory: 100Mi
  skipLatestRevCheck: false
  logger:
    tail: 100
    buffer: 5000
    sinceSeconds: 300
    fullScreenLogs: false
    textWrap: false
    showTime: false
  currentContext: default
  currentCluster: default
  keepMissingClusters: false
  clusters:
    default:
      namespace:
<<<<<<< HEAD
        active: vault
        lockFavorites: false
        favorites:
        - vault
        - prometheus
        - ingress-nginx
        - cert-manager
=======
        active: verimi-otip-production
        lockFavorites: false
        favorites:
        - verimi-otip-production
        - cert-manager
        - ingress-nginx
>>>>>>> 3dc2a0d (feat(scripts): flux installer and mtls cert generator)
        - kube-system
        - all
        - default
      view:
        active: pods
      featureGates:
        nodeShell: false
      portForwardAddress: localhost
  thresholds:
    cpu:
      critical: 90
      warn: 70
    memory:
      critical: 90
      warn: 70
  screenDumpDir: /tmp/k9s-screens-root
  disablePodCounting: false
