#!/bin/sh
xrandr --output LVDS1 --off
xrandr --output HDMI3 --mode 1920x1200 --pos 0x0 --rotate normal
xrandr --output VGA1 --mode 1280x1024 --pos 1920x176 --rotate normal
feh --bg-tile ~/wmconfig/wallpaper/tiled_1.jpg
