#!/bin/sh

podman run --rm -it \
  --user "$(id -u):$(id -g)" \
  --userns=keep-id \
  --security-opt label=disable \
  --volume "$(pwd):/home/$(whoami)/workspace:Z" \
  --workdir "/home/$(whoami)/workspace" \
  --env=TERM=$(echo ${TERM}) \
  quay.io/coreos/butane:release "$@"
