#!/bin/bash

IMAGE_NAME="localhost/neovim:latest"

podman run --rm -it \
  --user "$(id -u):$(id -g)" \
  --volume "${HOME}/.config/nvim:/home/dev/.config/nvim:Z" \
  --volume "${XDG_DATA_HOME:-$HOME/.local/share}/nvim:/home/dev/.local/share/nvim:Z" \
  --volume "${XDG_CACHE_HOME:-$HOME/.cache}/nvim:/home/dev/.cache/nvim:Z" \
  --volume "${XDG_STATE_HOME:-$HOME/.local/state}/nvim:/home/dev/.local/state/nvim:Z" \
  --volume "${PWD}:/workspace:Z" \
  --workdir /workspace \
  "${IMAGE_NAME}" "$@"
