#!/bin/sh

#podman run --rm -it --runtime=krun \
podman run --rm -it \
  --user "$(id -u):$(id -g)" \
  --userns=keep-id \
  --volume "$HOME/.config/copilot:/home/$(whoami)/.copilot:z" \
  --volume "$(pwd):/home/$(whoami)/workspace:z" \
  --workdir "/home/$(whoami)/workspace" \
  --env=TERM=$(echo ${TERM}) \
  localhost/copilot:latest "$@"
