#!/bin/bash
podman run --rm -it \
  --user "$(id -u):$(id -g)" \
  --userns=keep-id \
  --volume "$HOME/.config/coyote:/home/$(whoami):Z" \
  --volume "$(pwd):/home/$(whoami)/workspace:Z" \
  --workdir "/home/$(whoami)/workspace" \
  --env=TERM=$(echo ${TERM}) \
  localhost/coyote:latest $@
