#!/bin/sh

podman run --rm -it \
  --volume "$HOME/.config/gcloud:/root/.config/gcloud:ro" \
  --volume "$HOME/.kube:/root/.kube:ro" \
  --volume "$(pwd):/workspace" \
  --volume "${HOME}/.docker/config.json:/root/.docker/config.json:ro" \
  --workdir "/workspace" \
  --env=KUBECONFIG=/root/.kube/config \
  --env=TERM=$(echo ${TERM}) \
  localhost/flux:latest "$@"
