#!/bin/sh

podman run --rm -it \
  --user "$(id -u):$(id -g)" \
  --userns=keep-id \
  --volume "$HOME/.config/gcloud:/home/$(whoami)/.config/gcloud:ro" \
  --volume "$HOME/.kube:/home/$(whoami)/.kube:ro" \
  --volume "$HOME/.docker/config.json:/home/$(whoami)/.docker/config.json:ro" \
  --volume "$(pwd):/workspace:Z" \
  --workdir "/workspace" \
  --env=KUBECONFIG=/home/$(whoami)/.kube/config \
  --env=TERM=$(echo ${TERM}) \
  localhost/flux:latest "$@"
