#!/bin/sh

podman run --rm -it \
  --user "$(id -u):$(id -g)" \
  --userns=keep-id \
  --volume "$HOME/.config/gcloud:/home/$(whoami)/.config/gcloud:Z" \
  --volume "$HOME/.kube:/home/$(whoami)/.kube:Z" \
  --volume "$HOME/.ssh:/home/$(whoami)/.ssh:Z" \
  --volume "$(pwd):/workspace" \
  --volume "${HOME}/.docker/config.json:/home/$(whoami)/.docker/config.json:Z" \
  --workdir "/workspace" \
  localhost/gcloud:latest "$@"
