#!/bin/sh

podman run --rm -it \
  --volume "$HOME/.config/gcloud:/root/.config/gcloud:Z" \
  --volume "$HOME/.kube:/root/.kube:Z" \
  --volume "$HOME/.ssh:/root/.ssh:Z" \
  --volume "$(pwd):/workspace" \
  --workdir "/workspace" \
  gcr.io/google.com/cloudsdktool/google-cloud-cli:latest gcloud "$@"
