#!/bin/bash
podman run --rm -it --interactive \
  --user "$(id -u):$(id -g)" \
  --userns=keep-id \
  --env GOOGLE_API_KEY=$(pass private/google/vertex-api-key) \
  --env GOOGLE_GENAI_USE_VERTEXAI=true \
  --volume ~/.config/gemini:/home/$(whoami)/.gemini:Z \
  --volume "$(pwd):/home/$(whoami)/workspace:Z" \
  --workdir "/home/$(whoami)/workspace" \
  --env=TERM=$(echo ${TERM}) \
  localhost/gemini-cli:latest
