#!/bin/sh

podman run --rm -it \
  --user "$(id -u):$(id -g)" \
  --userns=keep-id \
  --volume "$HOME/.config/gcloud:/home/$(whoami)/.config/gcloud:Z" \
  --volume "$HOME/.kube:/home/$(whoami)/.kube:Z" \
  --volume "$HOME/.config/helm:/home/$(whoami)/.config/helm:Z" \
  --volume "$HOME/.cache/helm:/home/$(whoami)/.cache/helm:Z" \
  --volume "$(pwd):/workspace" \
  --volume "${HOME}/.docker/config.json:/home/$(whoami)/.docker/config.json:ro" \
  --workdir "/workspace" \
  --env=KUBECONFIG=/home/$(whoami)/.kube/config \
  --env=TERM=$(echo ${TERM}) \
  --env=EDITOR=nvim \
  localhost/helm:latest "$@"
