#!/bin/sh

podman run --rm -it \
  --user "$(id -u):$(id -g)" \
  --userns=keep-id \
  --volume "gcloud-config:/gcloud-config" \
  --env=CLOUDSDK_CONFIG=/gcloud-config \
  --volume "$HOME/.kube:/home/$(whoami)/.kube:ro" \
  --volume "$(pwd):/workspace" \
  --workdir "/workspace" \
  --env=KUBECONFIG=/home/$(whoami)/.kube/config \
  --env=TERM=$(echo ${TERM}) \
  --env=EDITOR=nvim \
  localhost/gcloud-istioctl:latest "$@"
