#!/bin/sh

podman run --rm -it \
  --user "$(id -u):$(id -g)" \
  --userns=keep-id \
  --security-opt label=disable \
  --volume "$HOME/.config/gcloud:/home/$(whoami)/.config/gcloud:Z" \
  --volume "$HOME/.kube:/home/$(whoami)/.kube:z" \
  --volume "$HOME/.config/k9s:/home/$(whoami)/.config/k9s:z" \
  --volume "$(pwd):/workspace" \
  --volume "${HOME}/.docker/config.json:/home/$(whoami)/.docker/config.json:z" \
  --workdir "/workspace" \
  --env=KUBECONFIG=/home/$(whoami)/.kube/config \
  --env=TERM=$(echo ${TERM}) \
  --env=EDITOR=nvim \
  localhost/gcloud-k9s:latest "$@"
