#!/bin/sh

podman run --rm -i \
  --user "$(id -u):$(id -g)" \
  --userns=keep-id \
  --volume "$HOME/.config/gcloud:/home/$(whoami)/.config/gcloud:Z" \
  --volume "$HOME/.kube:/home/$(whoami)/.kube:Z" \
  --volume "$(pwd):/workspace" \
  --workdir "/workspace" \
  --env=KUBECONFIG=/home/$(whoami)/.kube/config \
  --env=TERM=$(echo ${TERM}) \
  localhost/kubectl "$@"
