#!/usr/bin/python3
import logging
import os
import time
import select

from Xlib.display import Display
from subprocess import call

display = Display(os.environ.get("DISPLAY",":0.0"))
root = display.screen().root

def get_screen_size():
    return (root.get_geometry().width, root.get_geometry().height)
k = get_screen_size()

while True:
    j = get_screen_size()
    if j != k:
        call(['polybar-msg', 'cmd', 'restart'])
    k = j
    time.sleep(1)
