#! /usr/bin/env bash

# Kill if any other rofi instance is running
if pgrep -x "rofi"
then
    killall rofi
    exit
fi

chosen=$(printf "  Power Off\n  Restart\n  Suspend\n  Lock" | rofi -theme nord -p "Power menu" -dmenu -i)

case "$chosen" in
	"  Power Off") systemctl poweroff ;;
	"  Restart") systemctl reboot ;;
	"  Suspend") systemctl suspend ;;
	"  Lock") swaylock ;;
	*) exit 1 ;;
esac
