#!/bin/sh
if grep -q open /proc/acpi/button/lid/LID/state; then
    swaymsg output eDP-1 enable
    swaymsg input type:touchpad events disabled
else
    swaymsg output eDP-1 disable
    swaymsg input type:touchpad events enabled
fi
