#!/bin/sh
LAPTOP_OUTPUT="eDP-1"
LID_STATE_FILE="/proc/acpi/button/lid/LID0/state"

read -r LS < "$LID_STATE_FILE"

case "$LS" in
*open)   swaymsg output "$LAPTOP_OUTPUT" enable && swaymsg input type:touchpad events enabled && swaymsg input type:touch events enabled ;;
*closed) swaymsg output "$LAPTOP_OUTPUT" disable && swaymsg input type:touchpad events disabled && swaymsg input type:touch events disabled ;;
*)       echo "Could not get lid state" >&2 ; exit 1 ;;
esac
