#!/bin/sh

podman run --rm -it \
  --user "$(id -u):$(id -g)" \
  --userns=keep-id \
  --volume "$(pwd):/workspace" \
  --workdir "/workspace" \
  --env=TERM=$(echo ${TERM}) \
  localhost/tfsec:latest "$@"
